name: Arch Test Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-middle-script:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh

    - name: Run middle install script
      run: bash ./frontend/public/scripts/install.sh -s --os ubuntu --node-type relay --relay-name test-relay --contact-info uwu@gmail.com --or-port 9001 --dir-port  --traffic-limit nolimit --max-bandwidth nolimit --max-burst-bandwidth nolimit --enable-nyx-monitoring true

  test-exit-script:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh

    - name: Run exit install script
      run: bash ./frontend/public/scripts/install.sh -s --os ubuntu --node-type exit --relay-name test-relay --contact-info uwu@gmail.com --or-port 9001 --dir-port 9030 --traffic-limit nolimit --max-bandwidth nolimit --max-burst-bandwidth nolimit --enable-nyx-monitoring true --block-bad-ips true --dir-port 9030


  test-bridge-script:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh

    - name: Run bridge install script
      run: bash ./frontend/public/scripts/install.sh -s --os ubuntu --node-type bridge --relay-name test-relay --contact-info uwu@gmail.com --or-port 9001 --dir-port 9030 --traffic-limit nolimit --max-bandwidth nolimit --max-burst-bandwidth nolimit --enable-nyx-monitoring true --obsf4-port 9000