name: Ubuntu Test Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-middle-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run middle install script
      run: bash ./frontend/public/scripts/install.sh -s -- --node-type relay --relay-name testrelay --contact-info test@example.com --enable-ipv6 true --or-port 9001 --dir-port 9030 --traffic-limit '1 GB' --max-bandwidth '1 GB' --max-burst-bandwidth '1 GB' --enable-nyx-monitoring true

  test-exit-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run exit install script
      run: bash ./frontend/public/scripts/install.sh -s -- --node-type exit --relay-name testrelay --contact-info test@example.com --enable-ipv6 true --or-port 9001 --dir-port 9030 --traffic-limit '1 GB' --max-bandwidth '1 GB' --max-burst-bandwidth '1 GB' --enable-nyx-monitoring true


  test-bridge-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run bridge install script
      run: bash ./frontend/public/scripts/install.sh -s -- --node-type bridge --relay-name testrelay --contact-info test@example.com --enable-ipv6 true --or-port 9001 --dir-port 9030 --traffic-limit '1 GB' --max-bandwidth '1 GB' --max-burst-bandwidth '1 GB' --enable-nyx-monitoring true
